name: bilions_ui
description: Bilions UI components | This package is modified version of material UI with custom made alert, confirm, image preview, toast widgets.
version: 0.0.3
homepage: https://github.com/necessarylion/bilions_ui

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  logger:
  image_picker:
  flutter_svg:
  photo_view:
  intl:
  path:
  carousel_slider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
